### ISSUE TITLE
[BUG] Instructions for sample without the `managed_subscribe` feature are outdated

### ISSUE THREAD

**Issue by wilyle** [eclipse-ibeji/ibeji#49]
## Description

When trying to run a sample which does not use the `managed_subscribe` feature (such as the mixed property sample), running the `invehicle_digital_twin` package fails with the following error:

```
$ ./invehicle-digital-twin
[2023-09-28T22:25:26Z INFO  invehicle_digital_twin] The In-Vehicle Digital Twin Service has started.
[2023-09-28T22:25:26Z INFO  invehicle_digital_twin] The HTTP server is listening on address 'http://0.0.0.0:5010'
[2023-09-28T22:25:26Z INFO  invehicle_digital_twin] This service is not using Chariott.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "managed_subscribe_settings" not found', /home/wilyle/repos/ibeji/core/common/src/utils.rs:19:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Please update the documentation to include the correct build command with the `--no-default-features` flag. Alternatively, remove `managed_subscribe` as a default feature and update the documentation for the relevant samples to enable that feature during build

## Acceptance criteria

- [x] All (supported) samples have correct documentation on how to build them

**Comment by devkelley** [comment]
This was completed with the PR merged on Oct 6.
